//=========================================================
// src/EFM8OpenWindow_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB2_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

#include "UART1.h"
#include <stdio.h>


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  volatile long i = 0;
  uint8_t old_page;
  bool cmp0_output;
  bool cmp1_output;

  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  UART1_init();
  
  printf("OpenWindow V0.0\r\n");

  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

    for (i = 0; i < 200000; i++) {

    }
#define CMP_SFRPAGE 0x10

    old_page = SFRPAGE;
    SFRPAGE = CMP_SFRPAGE;
    cmp0_output = CMP0CN0 & CMP0CN0_CPOUT__BMASK;
    cmp1_output = CMP1CN0 & CMP1CN0_CPOUT__BMASK;
    printf("CMP0: %d, CMP1: %d\r\n", (int)cmp0_output, (int)cmp1_output);
    SFRPAGE = old_page;
  }                             
}
